export type PromptAnswer =
  | "program not found"
  | "command not found"
  | "help"
  | "login"
  | "register"
  | "just save command"
  | "wrong login length"
  | "to weak password"
  | "passwords does not match"
  | "not valid email format"
  | "login completed"
  | "wrong password"
  | "user not found"
  | "account creating error"
  | "name already in use"
  | "email already in use"
  | "account log in error";
